-- Runs only against synthetic boot programs and disposable images generated by test_scripting.py.
io.stdout:setvbuf('no')
local a = emu:getCPU(C.CPU.ARM11A)
local b = emu:getCPU(C.CPU.ARM11B)
local n = emu:getCPU(C.CPU.ARM9)
local function fails(fn) assert(not pcall(fn)) end
fails(function() emu:read8(0) end)
local starts, resets, frames = 0, 0, 0
callbacks:add('start', function() starts = starts + 1 end)
callbacks:add('reset', function() resets = resets + 1 end)
callbacks:add('frame', function() frames = frames + 1 end)
emu:start()
assert(starts == 1 and emu:currentFrame() == 0)
assert(a:readRegister('pc') == 0x10000)
assert(n:readRegister('pc') == 0xFFFF0000)
assert(emu:getPaths().mounted.sd == TESTDIR .. '/override.img')
fails(function() emu:getCPU('bad') end)
fails(function() emu:getCPU('ARM11C'):step() end)
fails(function() emu:write32(-1, 0) end)
fails(function() emu:readRange(0xFFFFFFFF, 2) end)
fails(function() emu.memory.boot9:write8(0, 0) end)
fails(function() emu.memory.fcramExt:read8(0) end)
fails(function() emu:writeRegister('cpsr', 0) end)
fails(function() emu:readRegister('invalid') end)
fails(function() emu:setPathOverride('sd', TESTDIR .. '/missing') end)
local retained = emu.memory.fcram
assert(retained:base() == 0x20000000 and retained:bound() == 0x28000000)
local bytes = string.char(0, 128, 255, 17)
emu:writeRange(0x20000FFE, bytes)
assert(emu:readRange(0x20000FFE, 4) == bytes)
emu:write32(0x20001FFF, 0x12345678)
assert(emu:read32(0x20001FFF) == 0x12345678)
a.physical:write32(0x20002FFF, 0xABCDEF12)
assert(a.physical:read32(0x20002FFF) == 0xABCDEF12)
retained:write32(0x3000, 0x87654321)
assert(emu:read32(0x20003000) == 0x87654321)

-- Independent CPU progress, banked registers, ARM/Thumb PC semantics.
a:writeRegister('sp', 0x1110)
a:writeRegister('cpsr', 0xD2)
a:writeRegister('sp', 0x2220)
a:writeRegister('cpsr', 0xD3)
assert(a:readRegister('sp') == 0x1110)
a:writeRegister('cpsr', 0xD2)
assert(a:readRegister('sp') == 0x2220)
a:writeRegister('cpsr', 0xD3)
local code, data = 0x20010000, 0x20020000
a:write32(code, 0xE3A0002A) -- mov r0, #42
a:write32(code + 4, 0xE5810000) -- str r0, [r1]
a:write32(code + 8, 0xE5912000) -- ldr r2, [r1]
a:write32(code + 12, 0xEAFFFFFE) -- b .
a:writeRegister('r1', data)
a:writeRegister('pc', code)
local hits = 0
local bp = a:setBreakpoint(function(info)
    assert(info.cpu == 'ARM11A' and info.pc == code and info.width == 0)
    hits = hits + 1; emu:pause()
end, code)
assert(emu:runFrame() == 'paused' and hits == 1)
assert(a:readRegister('pc') == code)
-- The current hit is skipped once, not fired recursively by stepping.
assert(a:step() == 'step' and a:readRegister('r0') == 42 and hits == 1)
assert(a:readRegister('pc') == code + 4)
assert(a:clearBreakpoint(bp))
local writes, reads = 0, 0
local wp = a:setRangeWatchpoint(function(info)
    assert(info.address == data and info.width == 4 and info.value == 42)
    if info.accessType == C.WATCHPOINT_TYPE.WRITE then
        writes = writes + 1; assert(info.pc == code + 4)
    else reads = reads + 1; assert(info.pc == code + 8) end
    -- Script inspection must not trigger the watchpoint.
    assert(a:read32(data) == 42)
end, data + 1, data + 3, C.WATCHPOINT_TYPE.RW)
assert(a:step() == 'step' and writes == 1)
assert(a:step() == 'step' and reads == 1 and a:readRegister('r2') == 42)
assert(a:clearBreakpoint(wp))
local fetches = 0
wp = a:setRangeWatchpoint(function() fetches = fetches + 1 end, code, code + 16, C.WATCHPOINT_TYPE.READ)
assert(a:step() == 'step' and fetches == 0)
a:clearBreakpoint(wp)
-- Step each other runnable ARM processor without advancing the selected one twice.
n:write32(0x08000000, 0xE3A03007)
n:write32(0x08000004, 0xEAFFFFFE)
n:writeRegister('pc', 0x08000000)
assert(n:step() == 'step' and n:readRegister('r3') == 7)
assert(b:step() == 'step')
a:write16(code + 0x40, 0x2409) -- Thumb movs r4, #9
a:write16(code + 0x42, 0xE7FE) -- Thumb b .
a:writeRegister('cpsr', 0xF3)
a:writeRegister('pc', code + 0x40)
assert(a:step() == 'step' and a:readRegister('r4') == 9 and a:readRegister('pc') == code + 0x42)
a:writeRegister('cpsr', 0xD3)
a:writeRegister('pc', code + 12)

emu:setKeys(0)
emu:addKey(C.KEY.A); emu:addKeys(1 << C.KEY.B)
assert(emu:getKey(C.KEY.A) and emu:getKeys() == 3)
emu:clearKey(C.KEY.A); emu:clearKeys(1 << C.KEY.B)
assert(emu:getKeys() == 0)
emu:pressScreen(319, 239); emu:releaseScreen()
emu:setLStick(-2047, 2047); emu:releaseLStick()
emu:pressHome(); emu:releaseHome()
fails(function() emu:pressScreen(320, 0) end)

-- Event snapshot semantics and rejection of recursive execution.
local removed, added = 0, 0
local second
local first = callbacks:add('frame', function()
    callbacks:remove(second)
    callbacks:add('frame', function() added = added + 1 end)
    fails(function() emu:runFrame() end)
    fails(function() emu:reset() end)
end)
second = callbacks:add('frame', function() removed = removed + 1 end)
assert(emu:runFrame() == 'frame' and frames == 1 and removed == 0 and added == 0)
callbacks:remove(first)
assert(emu:runFrame() == 'frame' and frames == 2 and added == 1)

-- Capture a red top screen, then green. Headless presentation must never stall.
local fb = 0x20040000
emu:writeRange(fb, string.rep(string.char(255, 0, 0, 255), 400 * 240)) -- RGBA packed framebuffer (alpha, blue, green, red)
a.physical:write32(0x10400468, fb)
a.physical:write32(0x10400470, 0)
a.physical:write32(0x10400474, 1)
a.physical:write32(0x10400490, 240 * 4)
assert(emu:runFrame() == 'frame')
emu:screenshot(TESTDIR .. '/red.png')
emu:writeRange(fb, string.rep(string.char(255, 0, 255, 0), 400 * 240))
assert(emu:runFrame() == 'frame')
emu:screenshot(TESTDIR .. '/green.png')
local buffer = console:createBuffer('status')
buffer:setSize(12, 2); buffer:print('ready'); assert(buffer:getX() == 5)
buffer:moveCursor(0, 1); buffer:print('done'); buffer:clear()
assert(buffer:getX() == 0 and buffer:rows() == 2)
fails(function() buffer:print(setmetatable({}, {__tostring = function() error('string conversion') end})) end)
assert(emu:currentFrame() >= 1)
print('memory, debugger, input, frames, screenshots passed')
-- Lua coroutines call the same bindings on their own stack.
local co = coroutine.create(function() assert(emu:currentFrame() == 4); coroutine.yield(emu:read8(data)) end)
local ok, value = coroutine.resume(co); assert(ok and value == 42)

print('coroutines passed')
-- A fresh breakpoint at the selected PC fires even when stepping.
assert(C.WATCHPOINT_TYPE.WRITE == 1 and C.WATCHPOINT_TYPE.READ == 2)
a:writeRegister('cpsr', 0xD3)
a:write32(code, 0xE1A00000)
a:writeRegister('pc', code)
local freshHits = 0
local fresh = a:setBreakpoint(function() freshHits = freshHits + 1 end, code)
assert(a:step() == 'step' and freshHits == 1)
a:clearBreakpoint(fresh)
-- Stepping another CPU preserves the pending suppression on ARM11A.
a:writeRegister('pc', code)
n:writeRegister('pc', 0x08000000)
n:write32(0x08000000, 0xE3A03007)
n:writeRegister('r3', 0)
local crossHits = 0
local cross = a:setBreakpoint(function() crossHits = crossHits + 1; emu:pause() end, code)
assert(emu:runFrame() == 'paused' and crossHits == 1)
assert(n:step() == 'step' and crossHits == 1 and n:readRegister('r3') == 7)
a:clearBreakpoint(cross)
-- Raw-domain code writes invalidate the instruction pipeline too.
a:writeRegister('pc', code)
emu.memory.fcram:write32(code - 0x20000000, 0xE3A0500B)
assert(a:step() == 'step' and a:readRegister('r5') == 11)
assert(emu:getKey(C.KEY.A) == 0)
local unused = callbacks:add('keysRead', function() error('unimplemented event') end)
callbacks:remove(unused)

-- Page-straddling MMIO preserves the byte-lane register behavior.
emu:write32(0x1013FFFF, 0x80808000)
assert(emu:read32(0x1013FFFF) == 0x80808000)
emu:write32(0x1013FFFF, 0)
fails(function() emu:read8("0x100") end)
assert(#emu.memory.fcram:readRange(0, 16 * 1024 * 1024) == 16 * 1024 * 1024)
-- ARM9 watchpoints report the bus-aligned address for an unaligned store.
n:write32(0x08000000, 0xE5810000)
n:writeRegister('r0', 42); n:writeRegister('r1', 0x08001003)
n:writeRegister('pc', 0x08000000)
local unalignedHits = 0
local unaligned = n:setWatchpoint(function(info)
    assert(info.address == 0x08001000 and info.newValue == 42 and info.accessType == 1)
    unalignedHits = unalignedHits + 1
end, 0x08001000, 1)
assert(n:step() == 'step' and unalignedHits == 1)
n:clearBreakpoint(unaligned)
-- Thumb breakpoints use the instruction address, with one paused-hit suppression.
a:write16(code + 0x40, 0x2409)
a:writeRegister('cpsr', 0xF3); a:writeRegister('pc', code + 0x40)
local thumbHits = 0
local thumb = a:setBreakpoint(function() thumbHits = thumbHits + 1; emu:pause() end, code + 0x40)
assert(a:step() == 'paused' and thumbHits == 1)
assert(a:step() == 'step' and thumbHits == 1 and a:readRegister('r4') == 9)
a:clearBreakpoint(thumb)

-- Overrides are pending until reboot, persist across resets, and can be cleared.
emu:setPathOverride('sd', TESTDIR .. '/second.img')
assert(emu:getPaths().mounted.sd == TESTDIR .. '/override.img')
assert(emu:getPaths().effective.sd == TESTDIR .. '/second.img')
emu:reset()
print('override reset passed')
assert(resets == 1 and emu:currentFrame() == 0)
assert(emu:getPaths().mounted.sd == TESTDIR .. '/second.img')
assert(retained:read32(0x3000) == 0) -- stale handle resolves to the new core
assert(emu:getKeys() == 0)
print('preparing failed reset')
os.rename(TESTDIR .. '/second.img', TESTDIR .. '/moved.img')
fails(function() emu:reset() end)
assert(emu:currentFrame() == 0 and emu:getPaths().mounted.sd == TESTDIR .. '/second.img')
print('failed reset preserved core')
emu:clearPathOverride('sd'); emu:reset()
assert(resets == 2 and emu:getPaths().mounted.sd == 'saved.img')
local stops = 0
callbacks:add('stop', function() stops = stops + 1 end)
emu:stop(); assert(stops == 1)
fails(function() retained:read8(0) end)
print('integration passed')
